### ISSUE TITLE
PersistentTaskController logging health monitoring logs under "System.String"

### ISSUE THREAD

**Issue by smerrell** [FubuMvcArchive/FubuTransportation#194]
Since logging with just `_logger.Info(() => ...` [here](https://github.com/DarthFubuMVC/FubuTransportation/blob/3d98c1b5d90e92a23b4415b01430e48c250aba87/src/FubuTransportation/Monitoring/PersistentTaskController.cs#L127) our logs are getting cluttered with messages like:

```
2015-02-09 18:57:50.1063  INFO System.String - Finished running task health monitoring on node FubuTransportationApp@SMERRELL02
```

I should have a Pull Request for this at some point, just wanted to make a note. Also, these messages can be filtered with this NLog filter

``` xml
<logger name="System.*" minlevel="Debug" writeTo="<nlog target here>" final="true">
  <filters>
    <when condition="starts-with('${message}', 'Finished running task health monitoring')" action="Ignore" />
  </filters>
</logger>
```

**Comment by jeremydmiller** [comment]
@smerrell @RyanHauert & I were talking about this this morning. I think our vote is that we'll completely eliminate ILogger.***(string) methods such that ILogger is only usable for semantic logging kinds of things and adjust fubu internal code accordingly.
